name             "whichsapp"
maintainer       "Greg Swallow"
maintainer_email "gswallow@indigobio.com"
description      "Simple cookbook for managing deployment of whichsapp"
version          "0.0.1"

depends "application"
depends "application_ruby"
depends "etcd"
depends "nginx"
depends "runit"
depends "logrotate"
