name             "whatsinstalled"
maintainer       "Greg Swallow"
maintainer_email "gswallow@indigobio.com"
description      "Simple cookbook for managing deployment of whatsinstalled"
version          "0.1.0"

depends "application"
depends "application_ruby"
depends "etcd"
depends "nginx"
depends "runit"
depends "logrotate"
