#! /bin/sh

### BEGIN INIT INFO
# Provides:          whichsapp_agent
# Required-Start:    $local_fs
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: Starts a simple version monitoring server
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin

case "$1" in
  start)
    cd /opt/whichsapp
    bundle exec ruby whichsapp_agent.rb start
	;;
  restart)
    cd /opt/whichsapp
    bundle exec ruby whichsapp_agent.rb stop
    bundle exec ruby whichsapp_agent.rb start
    ;;
  stop)
    cd /opt/whichsapp
    bundle exec ruby whichsapp_agent.rb stop
	;;
  *)
    ;;
esac

exit 0
